version: '3.8'

services:
  emprende:
    image: postgres:15
    container_name: emprende
    restart: unless-stopped
    environment:
      POSTGRES_DB: emprende
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
